site_name: AgileArchitect
docs_dir: ../manuscript/
pages:
- Architecture: 'index.md'
- Architecture Repository:
    - Introduction: '1. Introduction.md'
    - Guiding principles: '2. Guiding Principles.md'
    - Workflow: '10. Workflow.md'
    - Digital Delivery Method: '12. DigitalDeliveryMethod.md'
    - IAF: '13. IAF.md'
    - Rugged DevOps: '14. RuggedDevOps.md'
- Lessons:
    - Template Lessons: 'lessons/0. TemplateLessons.md'
- Guides:
    - Business Continuity: 'guides/1_Business_Continuity.md'
    #- 'Styling your docs': 'user-guide/styling-your-docs.md'
#- About:
#    - 'License': 'about/license.md'
#    - 'Release Notes': 'about/release-notes.md'
theme: readthedocs #cosmo
