site_name: Architecture Academy
google_analytics: ['UA-78514643-1', 'agilearchitect.azurewebsites.net']
docs_dir: ../manuscript/
theme: readthedocs
pages:
- Architecture Academy:
  - Introduction: 'index.md'
  - Culture of Collaboration: 'introduction/DevOps.md'
  - Social Science Analysis: 'introduction/Social_Science_Analysis.md'
  - Common Body of Knowledge: 'introduction/CBK.md'
- Architecture Disciplines:
  - Business Architect: 'disciplines/business_architect.md'
  - Information Architect: 'disciplines/information_architect.md'
  - Integration Architect: 'disciplines/information_architect.md'
  - Identity Architect: 'disciplines/identity_architect.md'
  - Project Architect: 'disciplines/project_architect.md'
  - Security Architect: 'disciplines/security_architect.md'
  - Software Architect: 'disciplines/software_architect.md'
- Lessons:
  - Architecture Repository: 'lessons/Architecture_Repository.md'
  - Business Architecture: 'lessons/Business_Architecture.md'
  - Collaboration Platform: 'lessons/CollaborationPlatform.md'
  - Information Architecture: 'lessons/Information_Architecture.md'
  - Integration Architecture: 'lessons/Integration_Architecture.md'
  - Identity Architecture: 'lessons/Identity_Architecture.md'
  - Project Architecture: 'lessons/Project_Architecture.md'
  - Security Architecture: 'lessons/Rugged_DevOps.md'
  - Software Architecture: 'lessons/Software_Architecture.md'
  - Stakeholder Communication: 'lessons/Stakeholder_Communication.md'
- Guides:
  - Architecture Repository: 'guides/Architecture_Repository.md'
  - Business Architetcure: 'guides/Business_Architecture.md'
  - Identity Architecture: 'guides/Identity_Architecture.md'
  - Information Architecture: 'guides/Information_Architecture.md'
  - Integration Architecture: 'guides/Integration_Architecture.md'
  - Project Architecture: 'guides/Project_Architecture.md'
  - Security Architecture: 'guides/Security_Architecture.md'
  - Software Architecture: 'guides/Software_Architecture.md'
  - Stakeholder Communication: 'guides/Stakeholder_Communication.md'
  - Risk Management: 'guides/Risk_Management.md'
- Useful Material:
  - Agile Manifesto: 'useful_material/Agile_Manifesto.md'
  - Archimate: 'useful_material/Archimate.md'
  - TechnoVision: 'useful_material/Technovision.md'
  - Global Identity Foundation: 'useful_material/Global_Identity_Foundation.md'  
- Ideas:
    - Ideas: 'ideas/README.md'
- About:
  - The Community: 'about/community.md'
  - License: 'about/license.md'
  - Release Notes: 'about/release_notes.md'
  - Acknowledgements: 'about/acknowledgements.md'
  - References: 'about/references.md'
