site_name: The Agile Architect
google_analytics: ['UA-78514643-1', 'agilearchitect.azurewebsites.net']
docs_dir: ../manuscript/
theme: readthedocs
pages:
- DevOps for Architecture: 'index.md'
- Introduction:
  - Background: 'introduction/1_Introduction.md'
  - Guiding principles: 'introduction/2_Guiding_Principles.md'
  - Workflow: 'introduction/3_Workflow.md'
  - Architecture Disciplines: 'introduction/4_Architecture_Disciplines.md'
  - Social Science Analysis: 'introduction/5_Social_Science_Analysis.md'
  - Common Body of Knowledge: 'introduction/6_CBK.md'
  - Tools: 'introduction/7_Tools.md'
- Lessons:
  - Tools and Techniques: 'lessons/1_Tools_and_Techniques.md'
  - Digital Delivery Method: 'lessons/2_Digital_Delivery_Method.md'
  - Rugged DevOps: 'lessons/3_Rugged_DevOps.md'
  - Practical Archimate: 'lessons/4_Practical_Archimate.md'
  - Information Architecture: 'lessons/5_Information_Architecture.md'
  - Identity Management Architecture: 'lessons/6_Identity_Management_Architecture.md'
  - Software Architecture Patterns: 'lessons/7_Software_architecture_patterns.md'
- Guides:
  - Overarching guide: 'guides/0_Overarching_Guide.md'
  - Business Continuity: 'guides/1_Business_Continuity.md'
  - Information  Security Requirements: 'guides/2_Information_Security_Requirements.md'
  - Stakeholder Communication: 'guides/3_Stakeholder_Communication.md'
  - Software Architecture Patterns: 'guides/4_Software_Architecture_Patterns.md'
  - Architecture Repository: 'guides/5_Architecture_Repository.md'
  - Information Architecture: guides/6_Information_Architecture.md
  - Business Architecture: 'guides/7_Business_Architecture.md'
  - Security Architecture: 'guides/8_Security_Architecture.md'
  - Risk Management: 'guides/9_Risk_Management.md'
  - Process Architetcure: 'guides/10_process_Architecture.md'
  - TechnoVision: 'guides/11_Technovision.md'
  - Integration Architecture: 'guides/12_Integration_Architecture.md'
  - Guide Template: 'guides/99_Template.md'
- Reference Architectures:
  - Introduction: 'refarch/0_Introduction.md'
  - Security Architecture: 'refarch/1_Security_Architecture.md'
- About:
  - The Community: 'about/community.md'
  - License: 'about/license.md'
  - Release Notes: 'about/release_notes.md'
  - Acknowledgements: 'about/acknowledgements.md'
  - References: 'about/references.md'
