site_name: The Agile Architect
google_analytics: ['UA-78514643-1', 'agilearchitect.azurewebsites.net']
docs_dir: ../manuscript/
pages:
- DevOps for Architecture: 'index.md'
- Introduction:
  - Background: '1_Introduction.md'
  - Guiding principles: '2. Guiding Principles.md'
  - Workflow: '10. Workflow.md'
- Lessons:
    - Introduction: 'lessons/0_Introduction.md'
    - Tools and Techniques: 'lessons/1_Tools_and_Techniques.md'
    - Digital Delivery Method: 'lessons/2_Digital_Delivery_Method.md'
    - Rugged DevOps: 'lessons/3_Rugged_DevOps.md'
    - Practical Archimate: 'lessons/4_Practical_Archimate.md'
    - Information Architecture: 'lessons/5_Information_Architecture.md'
    - Identity Management Architecture: 'lessons/6_Identity_Management_Architecture.md'
    - Software Architecture Patterns: 'lessons/7_Software_architecture_patterns.md'
- Guides:
    - Business Continuity: 'guides/1_Business_Continuity.md'
    - Information  Security Requirements: 'guides/2_Information_Security_Requirements.md'
    - Stakeholder Communication: 'guides/3_Stakeholder_Communication.md'
    - Software Architecture Patterns: 'guides/4_Software_Architecture_Patterns.md'
    - Architecture Repository: 'guides/5_Architecture_Repository.md'

    #- 'Styling your docs': 'user-guide/styling-your-docs.md'
#- About:
#    - 'License': 'about/license.md'
#    - 'Release Notes': 'about/release-notes.md'
theme: readthedocs #cosmo
