site_name: DEF Architecture
google_analytics: ['UA-78514643-1', 'agilearchitect.azurewebsites.net']
docs_dir: ../manuscript/
theme: readthedocs
extra_css: [extra.css]
pages:
- Table of Content:
  - Introduction: 'index.md'
  - Culture of Collaboration: 'introduction/DevOps.md'
  - Social Science Analysis: 'introduction/Social_Science_Analysis.md'
  - Common Body of Knowledge: 'introduction/CBK.md'
- Architecture Disciplines:
  - Business Architect: 'disciplines/business_architect.md'
  - Information Architect: 'disciplines/information_architect.md'
  - Integration Architect: 'disciplines/information_architect.md'
  - Identity Architect: 'disciplines/identity_architect.md'
  - Project Architect: 'disciplines/project_architect.md'
  - Security Architect: 'disciplines/security_architect.md'
  - Software Architect: 'disciplines/software_architect.md'
  - Storytelling(UX): 'disciplines/storytelling.md'
- Architecture Guides:
  - Architecture Repository: 'guides/Architecture_Repository.md'
  - Business Architecture: 'guides/Business_Architecture.md'
  - IAM Architecture: 'guides/Identity_Architecture.md'
  - Information Architecture: 'guides/Information_Architecture.md'
  - Integration Architecture: 'guides/Integration_Architecture.md'
  - Project Architecture: 'guides/Project_Architecture.md'
  - Risk Management: 'guides/Risk_Management.md'
  - Security Architecture: 'guides/Security_Architecture.md'
  - Software Architecture: 'guides/Software_Architecture.md'
  - Stakeholder Communication: 'guides/Stakeholder_Communication.md'
  - Storytelling(UX): 'guides/storytelling.md'
- Learn about:
  - Architecture Repository: 'learn/Architecture_Repository.md'
  - Business Architecture: 'learn/Business_Architecture.md'
  - Collaboration Platform: 'learn/CollaborationPlatform.md'
  - Cross functional: 'learn/CrossFunction.md'
  - Information Architecture: 'learn/Information_Architecture.md'
  - Integration Architecture: 'learn/Integration_Architecture.md'
  - Identity Architecture: 'learn/Identity_Architecture.md'
  - Project Architecture: 'learn/Project_Architecture.md'
  - Security Architecture: 'learn/Security_Architecture.md'
  - Software Architecture: 'learn/Software_Architecture.md'
  - Stakeholder Communication: 'learn/Stakeholder_Communication.md'
  - Storytelling: 'learn/storytelling.md'
- Useful Material:
  - Agile Manifesto: 'useful_material/Agile_Manifesto.md'
  - Archimate: 'useful_material/Archimate.md'
  - Capgemini IAF: 'useful_material/iaf.md'
  - Fair Institute: 'useful_material/FairInstitute.md'
  - Global Identity Foundation: 'useful_material/Global_Identity_Foundation.md'
  - TechnoVision: 'useful_material/Technovision.md'
- Ideas:
  - Going DEF: 'ideas/Going DEF.md'
- Proof of Concept:
  - Introduction: 'poc/introduction.md'
  - Home dialysis: 'poc/HomeDialysis.md'
- About:
  - Acknowledgements: 'about/acknowledgements.md'
  - License: 'about/license.md'
  - Philosophy: 'about/philosophy.md'
  - References: 'about/references.md'
  - Release Notes: 'about/release_notes.md'
  - The Community: 'about/community.md'
  - Want to contribute: 'about/contribute.md'
